apiVersion: v1
kind: Service
metadata:
  name: linker-backend-service
  namespace: linker-app
spec:
  type: NodePort # Internal only; the Ingress handles public access
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30020