apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
  namespace: linker-app
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
    accessControlAllowOriginList:
      - "http://charlesmonroe.online"
      - "https://charlesmonroe.online"
      - "http://www.charlesmonroe.online"
    accessControlMaxAge: 100
    addVaryHeader: true